# author: olaf
# tag: octosyllabic-log-automation-factory
# port config: 5555:5555
# volume: /opt/olaf:/var/olaf_volume:z

# pull base image
# FROM python:3-onbuild
FROM ubuntu:16.04

# set timezone
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# install dependecies
RUN apt update -y
RUN apt upgrade -y
RUN apt install -y p7zip-full
RUN apt install -y postgresql
RUN apt install -y rsync
RUN apt install -y ssh
RUN apt install -y unzip
RUN apt install -y vim

# installing and setting up cron
RUN apt install -y cron
RUN echo '*/2 * * * * root echo "$(date) was the last time I heard from cron." > /var/log/cron.log' >> /etc/crontab
RUN echo '0 7 * * * root python3 /var/octosyllabic-log-automation-factory/src/main.py --sendmail' >> /etc/crontab
RUN echo "" >> /etc/crontab
RUN touch /var/log/cron.log
# CMD ["cron"]

# ssh config
RUN mkdir /root/.ssh
COPY ./src/cfg/rsa_known_hosts /root/.ssh/known_hosts
COPY ./src/cfg/id_* /root/.ssh/
# needed in order to make shell capable of communicating with ssh-agent
RUN echo 'eval "$(ssh-agent)"' >> /root/.bashrc
RUN echo "ssh-add /root/.ssh/id_rsa" >> /root/.bashrc
RUN echo "StrictHostKeyChecking no" > /root/.ssh/ssh_config

# add and setup pgpass file
COPY ./src/cfg/.pgpass /root/.pgpass
RUN chmod 600 /root/.pgpass

# copy app files to the docker
COPY . /var/octosyllabic-log-automation-factory/

# install python at last because requirements file is required
RUN apt install -y python3 python3-dev python3-pip
RUN pip3 install -r /var/octosyllabic-log-automation-factory/requirements.txt

# define default run command
CMD ["/var/octosyllabic-log-automation-factory/docker_run.sh"]
